### ISSUE TITLE
train error

### ISSUE THREAD

**Issue by 942411526** [MMOCKING/RadarCam-Depth#6]
Begin training...
Epoch:  1
Traceback (most recent call last):
  File "/media/SSD_2TB/yx/project/RadarCam-Depth-main/RCNet/rcnet_train_zju.py", line 20, in <module>
    train(train_image_paths = train_image_paths,
  File "/media/SSD_2TB/yx/project/RadarCam-Depth-main/RCNet/rcnet_main.py", line 323, in train
    loss, loss_info = rcnet_model.compute_loss(
  File "/media/SSD_2TB/yx/project/RadarCam-Depth-main/RCNet/rcnet_model.py", line 154, in compute_loss
    loss = torch.nn.functional.binary_cross_entropy_with_logits(
  File "/media/SSD_2TB/yx/miniconda3/envs/rc-depth/lib/python3.10/site-packages/torch/nn/functional.py", line 3160, in binary_cross_entropy_with_logits
    raise ValueError("Target size ({}) must be the same as input size ({})".format(target.size(), input.size()))
ValueError: Target size (torch.Size([40, 1, 300, 100])) must be the same as input size (torch.Size([10, 1, 300, 100]))

**Comment by 942411526** [comment]
image, radar_point, bounding_boxes_list, ground_truth_depth = batch_data
            print("ground_truth_depth",ground_truth_depth.shape)     torch.Size([1, 40, 1, 300, 100])
